### PR TITLE
#170868490 Build register books endpoint

### PR DESCRIPTION
**Pull request by AbdoulNuru**
#### What does this PR do?
Have the add books endpoint built

#### Description of task to be completed?
Have the following endpoint working with validations
`POST /api/v1/books/`

#### How should this be manually tested?
- Clone this repo to your local repository using `git clone <repo link>`
- Install all project dependencies using `npm i`
- Create a .env file and add your database information(username, password, host)
- run `sequelize db:migrate` and check if the tables are created in your database.
- Test this endpoint using postman `POST /api/v1/books/`, pass the admin token in the headers.

#### What are the relevant pivotal tracker stories?
[#170868490](https://www.pivotaltracker.com/story/show/170868490)

#### Screenshots (if appropriate)
Screen Shot 2020-01-29 at 00 04 14
Screen Shot 2020-01-29 at 00 04 40
Screen Shot 2020-01-29 at 00 05 10
Screen Shot 2020-01-29 at 00 05 58

### CODE REVIEW

**Review by hakoemmy — APPROVED** [review]
Looks good to me

**Review by blaise82 — APPROVED** [review]
Looks Good to me.

**Comment by RusimbiPatrick** [comment]
Merge it

**Comment by izzett222** [comment]
It looks good to me

**Pull request merged**
